export interface RegisterPatientRequest {
  name: string,
  cpf: string,
  email: string,
  password: string,
  color: string,
  birthdate: string,
  motherName: string,
  fatherName: string,
  bloodType: string,
  zipCode: string,
  city: string,
  uf: string,
  neighborhood: string,
  street: string,
  complement: string,
  number: number,
  cell: string,
}